### ISSUE TITLE
Error: Could not query PAKDF server auth1.ripple.com

### ISSUE THREAD

**Issue by knaufk** [TNG/BlitzPay_Frontend#15]
I am getting this error, when logging in with my ripple trade account. We should find out, what this is about.

**Comment by steffen-rath** [comment]
I noticed the same thing. The error occurs not only in our app, but also on the ripple trade homepage, so it seems to be an issue in Ripple Trade itself.

**Comment by knaufk** [comment]
Nothing we can do here. Works again.
