### ISSUE TITLE
Make backend persist its data

### ISSUE THREAD

**Issue by steffen-rath** [TNG/BlitzPay_Frontend#8]
As a BlitzPay customer,

I want my events to be persisted on a permanent storage medium,

so that I do not have to recreate them when the server is restarted.

**Comment by fhinkel** [comment]
As a goat,

I want a web framework 

that scales like I do.
 
![image](https://cloud.githubusercontent.com/assets/101553/8216372/70c99c2e-1536-11e5-94af-6fce7107b780.png)

**Comment by knaufk** [comment]
Which database do you want do use? Couchbase? ;)

**Comment by steffen-rath** [comment]
Following a remark by Franzi, I am currently looking into MongoDB. Coming from an SQL backgorund, it takes a little effort to get used to it, but it appears to integrate quite seamlessly with JavaScript. Also, since it does not have a fixed column layout, it seems to make it easier to change the database structure if we decide to add new fields later on.

**Comment by knaufk** [comment]
NoSQL is definitely easier for us here and MongoDB is propbably a save choice. The question is if we should use Couchbase since we are Couchbase partners...

**Comment by steffen-rath** [comment]
Ready for review :) I also deployed in on "production". After a few hickups it seems to work now, but bug reports are welcome.
